config/routes.rb
Rails.application.routes.draw do
  resources :documents do
    collection do 
      get :deleted
    end

    resources :versions, only: [:destroy] do
      member do
        get :diff, to: 'versions#diff'
        patch :rollback, to: 'versions#rollback'
      end
    end
  end

  resources :versions, only: [] do
    member do
      patch :bringback
    end
  end

  resources :sessions, only: [:new, :create] do
    delete 'logout', on: :collection
  end
  root to: 'documents#index'
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :user

  # Declare this in your model to track every create, update, and destroy.  Each version of
  # the model is available in the `versions` association.
  #
  # Options:
  # :on           the events to track (optional; defaults to all of them).  Set to an array of
  #               `:create`, `:update`, `:destroy` as desired.
  # :class_name   the name of a custom Version class.  This class should inherit from `PaperTrail::Version`.
  # :ignore       an array of attributes for which a new `Version` will not be created if only they change.
  #               it can also aceept a Hash as an argument where the key is the attribute to ignore (a `String` or `Symbol`),
  #               which will only be ignored if the value is a `Proc` which returns truthily.
  # :if, :unless  Procs that allow to specify conditions when to save versions for an object
  # :only         inverse of `ignore` - a new `Version` will be created only for these attributes if supplied
  #               it can also aceept a Hash as an argument where the key is the attribute to track (a `String` or `Symbol`),
  #               which will only be counted if the value is a `Proc` which returns truthily.
  # :skip         fields to ignore completely.  As with `ignore`, updates to these fields will not create
  #               a new `Version`.  In addition, these fields will not be included in the serialized versions
  #               of the object whenever a new `Version` is created.
  # :meta         a hash of extra data to store.  You must add a column to the `versions` table for each key.
  #               Values are objects or procs (which are called with `self`, i.e. the model with the paper
  #               trail).  See `PaperTrail::Controller.info_for_paper_trail` for how to store data from
  #               the controller.
  # :versions     the name to use for the versions association.  Default is `:versions`.
  # :version      the name to use for the method which returns the version the instance was reified from.
  #               Default is `:version`.
  has_paper_trail class_name: 'DocumentVersion', meta: { author_username: :user_name, 
                                                         word_count: :count_word }

  def user_name
    user ? user.name : ''
  end

  def count_word
    content.split(' ').count
  end

end

app/models/document_version.rb
class DocumentVersion < PaperTrail::Version
  self.table_name = :document_versions

  default_scope { where.not(event: 'create') } 
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :documents

  def self.find_version_author(version)
    find(version.terminator)   
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    session[:user_id] ? User.find(session[:user_id]) : nil
  end

  def require_user
    redirect_to new_session_path unless current_user
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :require_user
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)
    @document.user_id = current_user.id

    if @document.save
      redirect_to documents_path, notice: "New document saved."
    else
      render :new
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    if @document.update(document_params)
      redirect_to edit_document_path(@document), notice: "Document updated."
    else
      render :edit
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def deleted
    @documents = DocumentVersion.where(event: 'destroy')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:name, :content, :user_id)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.where(name: params[:name]).first_or_create
    session[:user_id] = user.id
    redirect_to documents_path
  end

  def logout
    session[:user_id] = nil
    redirect_to documents_path
  end

end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  before_action :require_user
  before_action :set_document_and_version, only: [:diff, :rollback, :destroy]

  def bringback
    version = DocumentVersion.find(params[:id])
    @object = version.reify
    @object.save
    version.delete
    redirect_to root_path, notice: 'The object was successfully brought back!'
  end
  
  def diff
  end

  def rollback
    document = @version.reify
    document.save
    redirect_to edit_document_path(document)
  end

  def destroy
  end

  private

    def set_document_and_version
      @document = Document.find(params[:document_id])
      @version = @document.versions.find(params[:id])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper

  def find_version_author_name(version)
    user = User.find_version_author(version) 
    user ? user.name : ''
  end

  def diff(content1, content2)
    changes = Diffy::Diff.new(content1, content2, 
                    include_plus_and_minus_in_html: true, 
                    include_diff_info: true)
    changes.to_s.present? ? changes.to_s(:html).html_safe : 'No Changes'
  end

end

app/views/documents/_form.html.erb
<%= form_for(@document, { role: 'form' }) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_area :content, class: 'form-control document-text-area' %>
  </div>
  <div class='fr'>
    <%= link_to 'Back', documents_path, class: 'btn btn-danger' %>
    <%= f.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/documents/_versions.html.erb
<h2>Previous Versions</h2>

<table class='table'>
  <thead>
    <tr>
      <th>Index</th>
      <th>Date</th>
      <th>Author</th>
      <th>Event</th>
      <th>Word Count</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <%- document.versions.reverse.each do |version| %>
      <tr>
        <td><%= version.id %></td>
        <td><%= version.created_at %></td>
        <td><%= version.author_username %></td>
        <td><%= version.event.humanize %></td>
        <td><%= version.word_count %></td>
        <td><%= link_to 'Diff', diff_document_version_path(document, version) %></td>
        <td><%= link_to 'Rollback', rollback_document_version_path(document, version), method: 'PATCH' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/documents/deleted.html.erb
<h1>Bring back documents</h1>

<table class='table'>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Description</th>
      <th>Deleted by</th>
      <th>At</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document_version| %>
      <%- document = document_version.reify %>
      <tr>
        <td><%= document.id %></td>
        <td><%= document.name %></td>
        <td><%= document.content %></td>
        <td><%= find_version_author_name(document_version) %></td>
        <td><%= document.created_at %></td>

        <td><%= link_to 'Bringback', bringback_version_path(document_version), method: 'PATCH' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', documents_path %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

<%= render 'documents/versions', document: @document %>

app/views/documents/index.html.erb
<h1>Listing documents</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Creator</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.name %></td>
        <td><%= document.user_name %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'See Deleted Documents', deleted_documents_path %>
<br/>
<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PapertrailTuto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">PaperTrail - Jutsu #8</a>
      </div>
      <%- if current_user %>
        <div class='navbar-text'>
          Logged in as <%= current_user.name %>
          |
          <%= link_to 'Logout', logout_sessions_path, method: 'delete' %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="container">
    <%- if notice %><p class="notice bg-success"><%= notice %></p><% end %>
    <%- if alert %><p class="notice bg-danger"><%= alert %></p><% end %>
    <%= yield %>
  </div>
      
</body>
</html>

app/views/versions/diff.html.erb
<div class='row mt'>

  <div class='col-sm-12'>
    <h2><%= "Diff between Version #{@version.id} and Current Version" %></h2>
    <style><%= Diffy::CSS %></style>
    <div class='well diff'>
      <p>
        <strong>Name:</strong>
        <%= diff(@document.name, @version.reify.name) %>
      </p>

      <p>
        <strong>Content:</strong>
        <%= diff(@document.content, @version.reify.content) %>
      </p>
    </div>
    <p>
    <%= "Version authored by #{find_version_author_name(@version)} on #{@version.created_at} by '#{@version.event.humanize}'." %>
    </p>
  </div>

  

</div>

<div class='fr'>
  <%= link_to 'Back', edit_document_path(@document), class: 'btn btn-danger' %>
  <%= link_to 'Rollback', rollback_document_version_path(@document, @version), class: 'btn btn-primary', method: 'PATCH' %>
</div>